#cloud-config
package_upgrade: true

packages:
  - apache2

write_files:
  - content: |
      #!/bin/bash
      sed -i '10 a iface eth0 inet static' /etc/network/interfaces.d/50-cloud-init.cfg
      sed -i "11 a address $(curl -s -H Metadata:true 'http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/1/privateIpAddress?api-version=2017-08-01&format=text')" /etc/network/interfaces.d/50-cloud-init.cfg
      sed -i '12 a netmask 255.255.255.0' /etc/network/interfaces.d/50-cloud-init.cfg
      ifdown eth0 && ifup eth0
    path: /tmp/2ndIP.sh
    permissions: 0755
  - content: PGh0bWw+DQogICAgPGhlYWQ+DQogICAgICAgIDx0aXRsZT5XZWxjb21lIHRvIHtGUUROfSE8L3RpdGxlPg0KICAgIDwvaGVhZD4NCiAgICA8Ym9keT4NCiAgICAgICAgPGgxPlN1Y2Nlc3MhICBUaGUge0ZRRE59IHZpcnR1YWwgaG9zdCBpcyB3b3JraW5nITwvaDE+DQogICAgPC9ib2R5Pg0KPC9odG1sPg==
    encoding: b64
    path: /tmp/test.html
    permissions: 0755
  - content: |
      <!DOCTYPE html>
      <html lang="en">

      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <meta http-equiv="X-UA-Compatible" content="ie=edge">
          <title>{index_Title}</title>
          <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Raleway:400" rel="stylesheet"> 
          <link rel="stylesheet" href="./src/index.css">
      </head>

      <body>
          <div>
              <h1>This is your {heading} Test Site</h1>
          </div>
          <div class="images">
              <img id="azure" src="./src/azure.png" alt="Azure">
              <img src="./src/apache2.png" alt="Apache2">
          </div>
          <table>
              <tbody>
                  <tr>
                      <th>Site Location:</th>
                      <th class="info">{siteLocation}</th>
                  </tr>
                  <tr>
                      <th>VM Name</th>
                      <th class="info">{vmName}</th>
                  </tr>
                  <tr>
                      <th>OS Type:</th>
                      <th class="info">{osType}</th>
                  </tr>
                  <tr>
                      <th>Azure Resource Group</th>
                      <th class="info">{resourceGroup}</th>
                  </tr>
                  <tr>
                      <th>VM Size:</th>
                      <th class="info">{vmSize}</th>
                  </tr>
                  <tr>
                      <th>Private IP Address</th>
                      <th class="info">{privateIP}</th>
                  </tr>
                  <tr>
                      <th>Public IP:</th>
                      <th class="info">{publicIP}</th>
                  </tr>
                  <tr>
                      <th>Public FQDN</th>
                      <th class="info">{publicFQDN}</th>
                  </tr>
              </tbody>
          </table>
      </body>

      </html>
    path: /tmp/index2.html
    permissions: 0755
  - content: |
      <html>
          <head>
              <title>Welcome to {FQDN}!</title>
          </head>
          <body>
              <h1>Success!  The {FQDN} virtual host is working!</h1>
          </body>
      </html>
    path: /tmp/index.html
    permissions: 0755
  - content: |
      <VirtualHost *:80>
        ServerAdmin admin@{FQDN}
        ServerName {FQDN}
        ServerAlias www.{FQDN}
        DocumentRoot /var/www/{FQDN}/public_html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
      </VirtualHost>
    path: /tmp/index.conf
    permissions: 0755
  - content: |
      #!/bin/bash
      firstFQDN=$(cat /tmp/publicip1.txt)
      mkdir -p /var/www/$firstFQDN/public_html
      cp /tmp/index2.html /var/www/$firstFQDN/public_html/index.html
      sed -i "s#{publicFQDN}#$firstFQDN#g" /var/www/$firstFQDN/public_html/index.html
      cp /tmp/index.conf /etc/apache2/sites-available/$firstFQDN.conf
      sed -i "s#{FQDN}#$firstFQDN#g" /etc/apache2/sites-available/$firstFQDN.conf
      sed -i "s#{siteLocation}#$(curl -H Metadata:true "http://169.254.169.254/metadata/instance/compute/location?api-version=2017-08-01&format=text")#g" /var/www/$firstFQDN/public_html/index.html
      sed -i "s#{vmName}#$(curl -H Metadata:true "http://169.254.169.254/metadata/instance/compute/name?api-version=2017-08-01&format=text")#g" /var/www/$firstFQDN/public_html/index.html
      sed -i "s#{osType}#$(curl -H Metadata:true "http://169.254.169.254/metadata/instance/compute/osType?api-version=2017-08-01&format=text")#g" /var/www/$firstFQDN/public_html/index.html
      sed -i "s#{resourceGroup}#$(curl -H Metadata:true "http://169.254.169.254/metadata/instance/compute/resourceGroupName?api-version=2017-08-01&format=text")#g" /var/www/$firstFQDN/public_html/index.html
      sed -i "s#{vmSize}#$(curl -H Metadata:true "http://169.254.169.254/metadata/instance/compute/vmSize?api-version=2017-08-01&format=text")#g" /var/www/$firstFQDN/public_html/index.html
      sed -i "s#{privateIP}#$(curl -H Metadata:true "http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0/privateIpAddress?api-version=2017-08-01&format=text"")#g" /var/www/$firstFQDN/public_html/index.html
      sed -i "s#{publicIP}#$(curl -H Metadata:true "http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0/publicIpAddress?api-version=2017-08-01&format=text"")#g" /var/www/$firstFQDN/public_html/index.html
      chown -R apacheAdmin:apacheAdmin /var/www/$firstFQDN/public_html
      chmod -R 755 /var/www
      a2ensite $firstFQDN.conf
      a2dissite 000-default.conf
      service apache2 restart
    path: /tmp/firstSite.sh
    permissions: 0755
  - content: |
      #!/bin/bash
      secondFQDN=$(cat /tmp/publicip2.txt)
      mkdir -p /var/www/$secondFQDN/public_html
      cp /tmp/index.html /var/www/$secondFQDN/public_html/index.html
      sed -i "s#{FQDN}#$secondFQDN#g" /var/www/$secondFQDN/public_html/index.html
      cp /tmp/index.conf /etc/apache2/sites-available/$secondFQDN.conf
      sed -i "s#{FQDN}#$secondFQDN#g" /etc/apache2/sites-available/$secondFQDN.conf
      chown -R apacheAdmin:apacheAdmin /var/www/$secondFQDN/public_html
      chmod -R 755 /var/www
      a2ensite $secondFQDN.conf
      a2dissite 000-default.conf
      service apache2 restart
    path: /tmp/secondSite.sh
    permissions: 0755
runcmd:
  - [ sh, -c, "/tmp/2ndIP.sh" ]
  - [ sh, -c, "/tmp/firstSite.sh" ]
  - [ sh, -c, "/tmp/secondSite.sh" ]
  
output: {all: '| tee -a /var/log/cloud-init-output.log'}